# Generated by Django 4.1.1 on 2023-09-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='img',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
